### ISSUE TITLE
Extremely slow on emacs 25 for describe-function and describe-variable

### ISSUE THREAD

**Issue by vspinu** [DarwinAwardWinner/ido-completing-read-plus#126] opened 2017-07-23 13:03 UTC
After the the fix of #111 the ido for `describe-function` and `describe-variable` is extremely slow. Close to unusable actually. It seems to be performing full filtering on every character I type.

Also incremental refinement (`C-SPC`) has no effect.

**Comment by DarwinAwardWinner** [comment] 2017-07-23 14:27
Are you still on ido-ubiquitous 3.x (i.e. current MELPA stable)? The initial fix for #111 has actually been dropped in master (version 4.x) in favor of a more general solution that works for any dynamic completion table (see d7feee9079072faab6b38c1cd7279825c7094ec9). I haven't tagged a 4.x release yet because it's fairly new with a lot of new code, and I'm still testing it. I agree there are definitely noticeable delays for these two commands. Perhaps I should put the recalculation of dynamic collections on an idle timer.

I just tried C-SPC and it seemed to work for me (again, using 4.x). I typed `make-` and then C-SPC, and then all the presented matches had `make-` in them. 

In any case, I could implement a dynamic completion blacklist that turns off support for dynamic completion tables in specific functions. You would lose the dynamic loading of files but gain some speed.

**Comment by vspinu** [comment] 2017-07-24 09:33
I am actually on 4.x from MELPA proper (`ido-completing-read+-20170708.1116`). 

>  Perhaps I should put the recalculation of dynamic collections on an idle timer.

What part is takes so long, loading files? Isn't then it supposed to happen once per session? For me, those commands are slow on every invocation.

> I just tried C-SPC and it seemed to work for me

Hm, indeed works now. Will keep an eye on this one.

**Comment by DarwinAwardWinner** [comment] 2017-07-24 10:04
FYI the idle timer code is now in the bleeding-edge branch, if you wane to try it.

**Comment by DarwinAwardWinner** [comment] 2017-07-24 16:56
I can elaborate a little on the logic that ido-ubiquitous now uses for dynamic collections. If the collection is a function, rather than a list, ido-ubiquitous saves that function in a private variable so it can call it again as necessary. Previously, every time you typed or deleted a character, ido-cr+ would call `all-completions` on the empty string and your current input and then set the list of completions to the union of those two results. This worked pretty well, but it also meant that ido was updating the set of completions on every keypress, and it also meant that any dynamically-added completions could not support flex matching, since they would only be found and added to the list if the current input was a prefix of them.

Now, ido-cr+ generally waits until the user is idle for 0.25 seconds before doing any dynamic update. When it runs the update, it checks the user's input and every prefix of that input down to the empty string for completions, and takes the union of all of them plus the current list of completions. For example, if the user inputs "hello" and then goes idle, it will call `all-completions` with "", "h", "he", "hel", "hell", and "hello" and take the union of those with the current collection as the new collection. Because it can only add to the current collection, it uses a shortcut to avoid running `all-completions` on the same string twice, by starting at the longest common prefix of the current input and the input from the last time it updated. So if the last dynamic update was performed on "hi", then it skips "" and "h" since those completions have already been added, and it starts the update with "he". In addition, it will also call `all-completions` on the first available match (if any) and add those matches to the completion list. Finally, if the list of current matches gets narrowed down to 1 or 0 or the user presses TAB, a dynamic update is triggered immediately, because both ido and the user need to know whether or not they've really narrowed the list down to a single item.

This design should hopefully result in fewer user-noticeable slowdowns. Early in completion, dynamic updates are either done during idle time or when the user presses TAB. Later in completion when the options are narrowed down to a single match, dynamic updates are done immediately each time the user types a letter, but because there are fewer matches the update should not take very long.

**Comment by vspinu** [comment] 2017-07-24 21:33
Great! Thanks for all that work. Sounds quite elaborate.

When you say "dynamic completion" what do you mean more concretely? I feel like I am missing something essential there.

**Comment by DarwinAwardWinner** [comment] 2017-07-24 21:41
Basically, a collection can be a simple list of items, or some other static object. In that case, the set of possible completions is known completely ahead of time. Or it can be a function that returns all the possible completions for a given string, in which case it's possible for the set of possible completions to change as you type. For example, the new implementations of `describe-function` and `describe-variable` use this feature to auto-load files and add the symbols in those files to the completion list on the fly during completion. There are some other commands in core Emacs that also use this advanced feature of `completing-read`. This is what I'm calling dynamic completion, following the terminology of ivy-mode.

**Comment by vspinu** [comment] 2017-07-24 22:04
Thank you for the explanation. I recall people were talking about this years ago on emacs devel, but I have lost track of emacs development for the past year or so. Great this is feature is already there. 

I have tried the bleeding edge and it seems to be very fast indeed, but I got 

```
Error running timer ‘ido-cr+-update-dynamic-collection’: (wrong-number-of-arguments not 2) [3 times]
```
I guess it should be a typo somewhere.

**Comment by DarwinAwardWinner** [comment] 2017-07-24 22:09
Hmm, I don't see anything in the code that would cause that error, and the test suite currently passes with this version. Did you remember to restart Emacs after upgrading to make sure you aren't getting a weird combination of old and new? If that doesn't fix it, can you give me a backtrace, tell me exactly which Emacs version you're using, and tell me exactly what you did to trigger that error?

**Comment by vspinu** [comment] 2017-07-24 22:33
It might be an issue on my side. All I did was adding ido-ubiquitous repo to the load path and sticking a `(require 'ido-completing-read+)` before  `package-initialize`. So some messup with all those dependencies is expected. 

This is the backtrace

```el
Debugger entered--Lisp error: (wrong-number-of-arguments not 2)
  (not (member item) result)
  (if (not (member item) result) (progn (setq result (nconc result (list item))) (setq n-taken (+ n-taken 1))))
  (progn (setq item (car --cl-var--)) (if (not (member item) result) (progn (setq result (nconc result (list item))) (setq n-taken (+ n-taken 1)))) (if (>= n-taken 5) (setq --cl-var-- result --cl-var-- nil) t))
  (and (consp --cl-var--) (progn (setq item (car --cl-var--)) (if (not (member item) result) (progn (setq result (nconc result (list item))) (setq n-taken (+ n-taken 1)))) (if (>= n-taken 5) (setq --cl-var-- result --cl-var-- nil) t)))
  (while (and (consp --cl-var--) (progn (setq item (car --cl-var--)) (if (not (member item) result) (progn (setq result (nconc result (list item))) (setq n-taken (+ n-taken 1)))) (if (>= n-taken 5) (setq --cl-var-- result --cl-var-- nil) t))) (setq --cl-var-- (cdr --cl-var--)))
  (let* ((result (quote nil)) (n-taken 0) (--cl-var-- ido-cr+-previous-dynamic-update-texts) (item nil) (result nil) (n-taken 0) (--cl-var-- t) --cl-var--) (while (and (consp --cl-var--) (progn (setq item (car --cl-var--)) (if (not (member item) result) (progn (setq result (nconc result ...)) (setq n-taken (+ n-taken 1)))) (if (>= n-taken 5) (setq --cl-var-- result --cl-var-- nil) t))) (setq --cl-var-- (cdr --cl-var--))) (if --cl-var-- (progn result) --cl-var--))
  (setq ido-cr+-previous-dynamic-update-texts (let* ((result (quote nil)) (n-taken 0) (--cl-var-- ido-cr+-previous-dynamic-update-texts) (item nil) (result nil) (n-taken 0) (--cl-var-- t) --cl-var--) (while (and (consp --cl-var--) (progn (setq item (car --cl-var--)) (if (not (member item) result) (progn (setq result ...) (setq n-taken ...))) (if (>= n-taken 5) (setq --cl-var-- result --cl-var-- nil) t))) (setq --cl-var-- (cdr --cl-var--))) (if --cl-var-- (progn result) --cl-var--)))
  (progn (setq ido-cr+-previous-dynamic-update-texts (let* ((result (quote nil)) (n-taken 0) (--cl-var-- ido-cr+-previous-dynamic-update-texts) (item nil) (result nil) (n-taken 0) (--cl-var-- t) --cl-var--) (while (and (consp --cl-var--) (progn (setq item (car --cl-var--)) (if (not ... result) (progn ... ...)) (if (>= n-taken 5) (setq --cl-var-- result --cl-var-- nil) t))) (setq --cl-var-- (cdr --cl-var--))) (if --cl-var-- (progn result) --cl-var--))))
  (if remembered-new-string (progn (setq ido-cr+-previous-dynamic-update-texts (let* ((result (quote nil)) (n-taken 0) (--cl-var-- ido-cr+-previous-dynamic-update-texts) (item nil) (result nil) (n-taken 0) (--cl-var-- t) --cl-var--) (while (and (consp --cl-var--) (progn (setq item ...) (if ... ...) (if ... ... t))) (setq --cl-var-- (cdr --cl-var--))) (if --cl-var-- (progn result) --cl-var--)))))
  (let* ((ido-text (buffer-substring-no-properties (minibuffer-prompt-end) ido-eoinput)) (predicate (nth 2 ido-cr+-orig-completing-read-args)) (first-match (car ido-matches)) (remembered-new-string nil) (strings-to-check (cond ((null first-match) (list ido-text)) ((and first-match (s-prefix\? ido-text first-match)) (list first-match)) (t (list ido-text first-match)))) (new-completions (let* ((checked-strings (quote nil)) (--cl-var-- strings-to-check) (string nil) (result nil) (checked-strings nil)) (while (consp --cl-var--) (setq string (car --cl-var--)) (setq result (nconc result (ido-cr+-all-dynamic-completions string ido-cr+-dynamic-collection predicate :rmdups nil :prev-string ...))) (setq checked-strings (nconc checked-strings (list string))) (setq --cl-var-- (cdr --cl-var--))) result))) (if new-completions (progn (setq ido-cur-list (delete-dups (nconc ido-cur-list new-completions))) (let ((current-match (car ido-matches))) (if (and current-match (member current-match ido-cur-list)) (progn (setq ido-cur-list (ido-chop ido-cur-list current-match))))) (ido-cr+--debug-message "Updated completion candidates for dynamic collection because `ido-text' changed to %S. `ido-cur-list' now has %s elements" ido-text (length ido-cur-list)) (setq ido-rescan t) (ido-set-matches) (if ido-cr+-exhibit-pending nil (ido-tidy) (ido-exhibit)))) (let* ((--cl-var-- strings-to-check) (new-text nil)) (while (consp --cl-var--) (setq new-text (car --cl-var--)) (cond ((s-prefix\? new-text (car ido-cr+-previous-dynamic-update-texts)) nil) ((s-prefix\? (car ido-cr+-previous-dynamic-update-texts) new-text) (let* ((v ido-cr+-previous-dynamic-update-texts)) (setcar v new-text))) (t (setq remembered-new-string t) (setq ido-cr+-previous-dynamic-update-texts (cons new-text ido-cr+-previous-dynamic-update-texts)))) (setq --cl-var-- (cdr --cl-var--))) nil) (if remembered-new-string (progn (setq ido-cr+-previous-dynamic-update-texts (let* ((result (quote nil)) (n-taken 0) (--cl-var-- ido-cr+-previous-dynamic-update-texts) (item nil) (result nil) (n-taken 0) (--cl-var-- t) --cl-var--) (while (and (consp --cl-var--) (progn ... ... ...)) (setq --cl-var-- (cdr --cl-var--))) (if --cl-var-- (progn result) --cl-var--))))))
  (progn (let* ((ido-text (buffer-substring-no-properties (minibuffer-prompt-end) ido-eoinput)) (predicate (nth 2 ido-cr+-orig-completing-read-args)) (first-match (car ido-matches)) (remembered-new-string nil) (strings-to-check (cond ((null first-match) (list ido-text)) ((and first-match (s-prefix\? ido-text first-match)) (list first-match)) (t (list ido-text first-match)))) (new-completions (let* ((checked-strings (quote nil)) (--cl-var-- strings-to-check) (string nil) (result nil) (checked-strings nil)) (while (consp --cl-var--) (setq string (car --cl-var--)) (setq result (nconc result ...)) (setq checked-strings (nconc checked-strings ...)) (setq --cl-var-- (cdr --cl-var--))) result))) (if new-completions (progn (setq ido-cur-list (delete-dups (nconc ido-cur-list new-completions))) (let ((current-match (car ido-matches))) (if (and current-match (member current-match ido-cur-list)) (progn (setq ido-cur-list ...)))) (ido-cr+--debug-message "Updated completion candidates for dynamic collection because `ido-text' changed to %S. `ido-cur-list' now has %s elements" ido-text (length ido-cur-list)) (setq ido-rescan t) (ido-set-matches) (if ido-cr+-exhibit-pending nil (ido-tidy) (ido-exhibit)))) (let* ((--cl-var-- strings-to-check) (new-text nil)) (while (consp --cl-var--) (setq new-text (car --cl-var--)) (cond ((s-prefix\? new-text (car ido-cr+-previous-dynamic-update-texts)) nil) ((s-prefix\? (car ido-cr+-previous-dynamic-update-texts) new-text) (let* (...) (setcar v new-text))) (t (setq remembered-new-string t) (setq ido-cr+-previous-dynamic-update-texts (cons new-text ido-cr+-previous-dynamic-update-texts)))) (setq --cl-var-- (cdr --cl-var--))) nil) (if remembered-new-string (progn (setq ido-cr+-previous-dynamic-update-texts (let* ((result ...) (n-taken 0) (--cl-var-- ido-cr+-previous-dynamic-update-texts) (item nil) (result nil) (n-taken 0) (--cl-var-- t) --cl-var--) (while (and ... ...) (setq --cl-var-- ...)) (if --cl-var-- (progn result) --cl-var--)))))))
  (if (and (ido-cr+-active) ido-cr+-dynamic-collection) (progn (let* ((ido-text (buffer-substring-no-properties (minibuffer-prompt-end) ido-eoinput)) (predicate (nth 2 ido-cr+-orig-completing-read-args)) (first-match (car ido-matches)) (remembered-new-string nil) (strings-to-check (cond ((null first-match) (list ido-text)) ((and first-match ...) (list first-match)) (t (list ido-text first-match)))) (new-completions (let* ((checked-strings ...) (--cl-var-- strings-to-check) (string nil) (result nil) (checked-strings nil)) (while (consp --cl-var--) (setq string ...) (setq result ...) (setq checked-strings ...) (setq --cl-var-- ...)) result))) (if new-completions (progn (setq ido-cur-list (delete-dups (nconc ido-cur-list new-completions))) (let ((current-match ...)) (if (and current-match ...) (progn ...))) (ido-cr+--debug-message "Updated completion candidates for dynamic collection because `ido-text' changed to %S. `ido-cur-list' now has %s elements" ido-text (length ido-cur-list)) (setq ido-rescan t) (ido-set-matches) (if ido-cr+-exhibit-pending nil (ido-tidy) (ido-exhibit)))) (let* ((--cl-var-- strings-to-check) (new-text nil)) (while (consp --cl-var--) (setq new-text (car --cl-var--)) (cond ((s-prefix\? new-text ...) nil) ((s-prefix\? ... new-text) (let* ... ...)) (t (setq remembered-new-string t) (setq ido-cr+-previous-dynamic-update-texts ...))) (setq --cl-var-- (cdr --cl-var--))) nil) (if remembered-new-string (progn (setq ido-cr+-previous-dynamic-update-texts (let* (... ... ... ... ... ... ... --cl-var--) (while ... ...) (if --cl-var-- ... --cl-var--))))))))
  ido-cr+-update-dynamic-collection()
  apply(ido-cr+-update-dynamic-collection nil)
  timer-event-handler([t 0 0 250000 nil ido-cr+-update-dynamic-collection nil idle 0])
  read-from-minibuffer("Describe variable: " "" (keymap (C-return . ido-select-text) keymap (4 . ido-magic-delete-char) (6 . ido-magic-forward-char) (2 . ido-magic-backward-char) (63 . ido-completion-help) (left . ido-prev-match) (right . ido-next-match) (0 . ido-restrict-to-matches) (27 keymap (32 . ido-take-first-match)) (67108896 . ido-restrict-to-matches) (26 . ido-undo-merge-work-directory) (20 . ido-toggle-regexp) (67108908 . ido-prev-match) (67108910 . ido-next-match) (19 . ido-next-match) (18 . ido-prev-match) (16 . ido-toggle-prefix) (13 . ido-exit-minibuffer) (10 . ido-select-text) (32 . ido-complete-space) (9 . ido-complete) (5 . ido-edit-input) (3 . ido-toggle-case) (1 . ido-toggle-ignore) keymap (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the minibuffer") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuffer") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "
" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . minibuffer-keyboard-quit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil nil)
  ido-read-internal(list "Describe variable: " nil nil t nil)
  #[(prompt choices &optional _predicate require-match initial-input hist def _inherit-input-method) "\306\211\211\307\310 \210\311\312\f
&-\207" [choices ido-choice-list ido-context-switch-command ido-directory-too-big ido-directory-nonreadable ido-current-directory nil ignore ido-common-initialization ido-read-internal list prompt hist def require-match initial-input] 7 ("/home/vspinu/bin/emacs/lisp/ido.elc" . 123314)]("Describe variable: " ("" "diary-included-files" "previous-system-messages-locale" "svn-status-default-log-arguments" "org-table-any-line-regexp" "cider-popup-buffer-mode-hook" "message-required-headers" "gdb-script-syntax-propertize-function" "input-method-verbose-flag" "reftex-default-bibliography" "custom-face-menu" "ispell-menu-map-needed" "org-emphasis-regexp-components" "mml-secure-smime-sign-with-sender" "ess-r-symbol-pattern" "inhibit-modification-hooks" "ess-save-lastvalue-command" "defun-prompt-regexp" "svn-info-mode-map" "clojure-docstring-fill-column" "byte-compile-last-position" "org-agenda-regexp-filter-preset" "svn-prop-edit-mode-menu" "imagemagick-types-inhibit" "vc-checkout-hook" "inferior-sml-mode-map" "svn-status-changelog-style" "message-kill-actions" "dired-before-readin-hook" "package-menu--new-package-list" "sp-autowrap-region" "tramp-cache-data" "r-function-call-face" "org-babel-results-keyword" "projectile-tags-file-name" "message-send-mail-function" "calendar-debug-sexp" "svn-status-mode-line-process-status" "menu-bar-edit-sort-menu" "cider-repl-history-display-styles" "nxml-mode-hook" "highlight-nonselected-windows" "symbols-consed" "julia-function-regex" "byte-compile-const-variables" "org-table-export-default-format" "default-sendmail-coding-system" "org-footnote-auto-label" "org-store-link-plist" "byte-compile-error-on-warn" ...) #[257 "r\300q\210\211\301N\206
```

This is `GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-06-28`

**Comment by DarwinAwardWinner** [comment] 2017-07-24 23:25
Weird, the really was an error in the code. It should have thrown an error on every dynamic update, yet somehow the test suite still passed. In any case, it's fixed now.

**Comment by vspinu** [comment] 2017-07-25 21:37
Confirming that it's fixed. Thanks!

As to my C-SPC issue the reset occurs when there are no-more candidates. For instance, `C-h v` then `popup C-SPC type`. You should see words with type but no popup.

**Comment by DarwinAwardWinner** [comment] 2017-07-25 23:40
I'm not sure I understand. C-SPC runs `ido-restrict-to-matches`, which means that in your example, you should see completions with *both* type and popup in them, which is exactly what I get when I try it.

**Comment by vspinu** [comment] 2017-07-26 07:02
In my case I don't have symbols with both popup and type in them. So I am getting a lot of symbols with `type` in them but no popup. Like `type-break-mode`. Do you see that?

**Comment by DarwinAwardWinner** [comment] 2017-07-28 19:59
No, it's not working the same for me. Do you have C-SPC bound to something other than `ido-restrict-to-matches`? What you're describing sounds like the opposite.

**Comment by vspinu** [comment] 2017-07-28 22:32
Yes, `ido-restric-to-matches`. I cannot investigate this further at the moment. It might be my issue indeed due to the way I fetch ido-ubiquitous. I will wait till you push this to master/MELPA and check again. Thanks for all the work and input!

**Comment by DarwinAwardWinner** [comment] 2017-08-07 22:09
I've finally tagged a 4.x release, which should propagate to MELPA soon. Please let me know if this issue is still a problem or if it's fixed.

**Comment by vspinu** [comment] 2017-08-11 10:52
I have tried it out from MELPA, much faster but same awkward result with `C-SPC`, it just adds many more irelevant candidates after the dynamic update has happened. As if the dynamic update disregards the restriction to matches.

**Comment by DarwinAwardWinner** [comment] 2017-08-11 15:59
I think the dynamic update probably does ignore the restriction. I'll have to look into this.

**Comment by DarwinAwardWinner** [comment] 2017-08-13 01:25
Ok, I've confirmed that the dynamic updating is definitely ignoring restrictions. I'm going to open a separate issue for that.

**Closed by DarwinAwardWinner** 2017-08-13 01:25 UTC
